### ISSUE TITLE
pod5 view fails with polars.exceptions.ColumnNotFoundError: not_set

### ISSUE THREAD

**Issue by janpb** [nanoporetech/pod5-file-format#104]
I follow the example  the dorado example to [speed up duplex read basecalling](https://github.com/nanoporetech/dorado#improving-the-speed-of-duplex-basecalling). 

Using the command pod5 view on a directory or single pod5 file fails with 
`polars.exceptions.ColumnNotFoundError: not_set`  

pod5 version:
```
$: pod5 --version
Pod5 version: 0.3.2
```
command:

` $: POD5_DEBUG=1 pod5 view PAS44726_481864cc_f61fb9b5_111.pod5`

This fails and produces two log files:
 - [2023-12-22--17-09-25-main-pod5.log](https://github.com/nanoporetech/pod5-file-format/files/13754183/2023-12-22--17-09-25-main-pod5.log)
 -  [2023-12-22--17-09-26-p-1781702-pod5.log](https://github.com/nanoporetech/pod5-file-format/files/13754184/2023-12-22--17-09-26-p-1781702-pod5.log)

It seems the read attribute  `not_set` is not recognized by `pod5 view` as it is not listed in when running `pod5 view -L`. 

pod5 inspect does work, e.g. output for a read from the analyzed pod5: 

```
$: pod5 inspect read PAS44726_481864cc_f61fb9b5_111.pod5 c8e86777-897e-4873-ba84-040cffe4d35a

read_id: c8e86777-897e-4873-ba84-040cffe4d35a
read_number:    14863
start_sample:   27255755
median_before:  198.2138671875
channel data:
        channel: 2396
        well: 2
        pore_type: not_set
end reason:
        name: signal_positive
        forced: False
calibration:
        offset: -242.0
        scale: 0.1870698481798172
samples:
        sample_count: 120819
        byte_count: 109216
        compression ratio: 0.452
run info:
        acquisition_id: f61fb9b56665a240e0c28507388f35bcd690461d
        acquisition_start_time: 2023-11-30 07:59:08.841000+00:00
        adc_max: 2047
        adc_min: 0
        context_tags: {'barcoding_enabled': '0', 'experiment_type': 'genomic_dna', 'local_basecalling': '0', 'package': 'bream4', 'package_version': '7.7.6', 'sample_frequency': '5000', 'selected_speed_bases_per_second': '400', 'sequencing_kit': 'sqk-lsk114-xl'}
        experiment_name: 20231130_PUM23-021_run1_prom
        flow_cell_id: PAS44726
        flow_cell_product_code: FLO-PRO114M
        protocol_name: sequencing/sequencing_PRO114_DNA_e8_2_400K:FLO-PRO114M:SQK-LSK114-XL:400
        protocol_run_id: 481864cc-8b0a-4e2d-ad3c-277ab74de980
        protocol_start_time: 2023-11-30 07:57:29.564000+00:00
        sample_id: 20231130_lilie_021B1A_prom
        sample_rate: 5000
        sequencing_kit: sqk-lsk114-xl
        sequencer_position: 3A
        sequencer_position_type: PromethION
        software: MinKNOW 23.07.12 (Bream 7.7.6, Core 5.7.5, Dorado 7.1.4+d7df870c0)
        system_name: PC24B189
        system_type: PromethION 24
        tracking_id: {'asic_id': '0004A30B001D6B1E', 'asic_id_eeprom': '0004A30B001D6B1E', 'asic_temp': '48.767216', 'asic_version': 'Unknown', 'configuration_version': '5.7.11', 'data_source': 'real_device', 'device_id': '3A', 'device_type': 'promethion', 'distribution_status': 'stable', 'distribution_version': '23.07.12', 'exp_script_name': 'sequencing/sequencing_PRO114_DNA_e8_2_400K:FLO-PRO114M:SQK-LSK114-XL:400', 'exp_script_purpose': 'sequencing_run', 'exp_start_time': '2023-11-30T08:59:08.841119+01:00', 'flow_cell_id': 'PAS44726', 'flow_cell_product_code': 'FLO-PRO114M', 'guppy_version': '7.1.4+d7df870c0', 'heatsink_temp': '34.117973', 'host_product_code': 'PRO-PRC024', 'host_product_serial_number': 'PC24B189', 'hostname': 'PC24B189', 'hublett_board_id': '0001238ca5e27cff', 'hublett_firmware_version': '2.1.10', 'installation_type': 'nc', 'is_simulated': '0', 'operating_system': 'ubuntu 20.04', 'protocol_group_id': '20231130_PUM23-021_run1_prom', 'protocol_run_id': '481864cc-8b0a-4e2d-ad3c-277ab74de980', 'protocol_start_time': '2023-11-30T08:57:29.564030+01:00', 'protocols_version': '7.7.6', 'run_id': 'f61fb9b56665a240e0c28507388f35bcd690461d', 'sample_id': '20231130_lilie_021B1A_prom', 'satellite_board_id': '013e56b41f2058f4', 'satellite_firmware_version': '2.3.0', 'sequencer_hardware_revision': '', 'sequencer_product_code': 'PRO-SEQ
```
